FC = gfortran
FFLAGS = -O3
LIBS = -llapack
LDFLAGS = -L/usr/lib

# How to make object files from Fortran 77 files.
%.o: %.f
	$(FC) $(FFLAGS) $(LDFLAGS) -c -o $@ $<

# How to make object files from Fortran 90 files.
%.o: %.f90
	$(FC) $(FFLAGS) $(LDFLAGS) -c -o $@ $<

# How to make object files from Fortran 90 preprocessor files.
%.o: %.F90
	$(FC) $(FFLAGS) $(LDFLAGS) -c -o $@ $<

all: cylinder expvalue eigenproblem

cylinder: cylinder.o
	$(FC) $(FFLAGS) -o $@ cylinder.o $(LDFLAGS) $(LIBS)

expvalue: expvalue.o
	$(FC) $(FFLAGS) -o $@ expvalue.o $(LDFLAGS) $(LIBS)

eigenproblem: eigenproblem.o
	$(FC) $(FFLAGS) -o $@ eigenproblem.o $(LDFLAGS) $(LIBS)

clean:
	rm -f *.o
	rm -f cylinder expvalue eigenproblem

.PHONY: all clean

